### ISSUE TITLE
No longer works in 0.9.21

### ISSUE THREAD

**Issue by aptly-io** [python-cmd2/cmd2-abbrev#2]
Seems that self.keywords is no longer in the implementation of Cmd2.

cleaner> set debug true
debug - was: False
now: True
> h world
Traceback (most recent call last):
  File "/home/dev/venv37/lib/python3.7/site-packages/cmd2/cmd2.py", line 1536, in onecmd_plus_hooks
    data = func(data)
  File "/home/dev/venv37/lib/python3.7/site-packages/cmd2_abbrev/abbrev.py", line 25, in cmd2_abbrev_hook
    funcs = [func for func in self.keywords if func.startswith(data.statement.command)]
AttributeError: 'Shell' object has no attribute 'keywords'

**Comment by kotfu** [comment]
Yeah, `cmd2` has had a number of breaking changes recently. I'll have a look at this.

**Comment by kotfu** [comment]
Got it fixed. I'll push a new release to pypi this weekend.

**Comment by kotfu** [comment]
Release 1.0.2 just pushed to https://pypi.org/project/cmd2-abbrev/

**Comment by aptly-io** [comment]
Works as expected!
